### ISSUE TITLE
arweave.png.png not found

### ISSUE THREAD

**Issue by Xaber20110202** [arconnectio/ArConnect#100]
When a transaction is sent using arweave.js, an animation effect may appear in the bottom right corner of the page. However, the image file arweave.png.png currently in use does not exist.
<img width="274" alt="image" src="https://github.com/arconnectio/ArConnect/assets/6246962/f9786710-aee5-46e5-8f6e-6e1c03ca9c59">

**Comment by martonlederer** [comment]
Solved in 1.0
