### ISSUE TITLE
Implement signMessage and deprecate signature

### ISSUE THREAD

**Issue by angrymouse** [arconnectio/ArConnect#103]
Pure RSA signature method is not secure. You can easily sign arweave transactions with it, without any knowledge from user that he signs something. This will be honeypot for various scams as soon as arweave eco gets popular. 
I propose to take signMessage method from arweave.app ( https://github.com/jfbeats/ArweaveWebWallet/blob/cc6cbeaaa502671b6e362c066bebe252dc19998c/src/providers/Arweave.ts#L209 ), which does hash message before signing it. This way we can achieve almost any logic that you would need to achieve using signature method, while it being much more secure (as you cannot sign arweave transactions with it).

**Comment by angrymouse** [comment]
CC @martonlederer

**Comment by martonlederer** [comment]
Yes I can confirm this is planned and is the next thing on our roadmap.

**Comment by angrymouse** [comment]
Thank you. I believe it's important step for securing arweave apps

**Comment by martonlederer** [comment]
Resolved via #107. Update is staging
