### ISSUE TITLE
arconnect v1.0.5 window.arweaveWallet undefined

### ISSUE THREAD

**Issue by Xaber20110202** [arconnectio/ArConnect#108]
arconnect v1.0.5 window.arweaveWallet undefined and the arweaveWalletLoaded event nerver emit

**Comment by martonlederer** [comment]
Seems like this is a production error, because development mode works just fine. Will look into this today.

**Comment by martonlederer** [comment]
Just published the fixed version on the chrome web store. Make sure to update to beta v1.0.8.
