### ISSUE TITLE
migration process makes it seem like you need to re-enter the seed

### ISSUE THREAD

**Issue by tzarebczan** [arconnectio/ArConnect#120]
When you migrate from the previous version, it still shows you a seed entry box. This is optional, but it was confusing at first as it makes it seem like it's asking for the old seed. If you continue, you get your wallet. If you re-add, you still get your single account added.

**Comment by tzarebczan** [comment]
Actually, it looks like it adds the account without a seed, and therefore can't be used (can't sign in / export).

**Comment by MattSoloing** [comment]
Thanks you for the feedback.  We reworked the onboarding in v1.0.7

https://github.com/arconnectio/ArConnect/releases/tag/1.0.7
