### ISSUE TITLE
Clicking the Firefox ArConnect extension does not show the extension

### ISSUE THREAD

**Issue by xylophonez** [arconnectio/ArConnect#22]
I'm seeing just a white line flash where the extension's panel should be.

![2021-06-14-151356_238x277_scrot](https://user-images.githubusercontent.com/69069725/121890626-39ab2900-cd23-11eb-98a4-374b604cd898.png)

**Comment by martonlederer** [comment]
Hey there, the Firefox extension is still experimental and we are facing some issues with it, but I'll take a look at this asap
