### ISSUE TITLE
Verto Fee remains high before tx commit finalization

### ISSUE THREAD

**Issue by pctj101** [arconnectio/ArConnect#32]
To my surprise, during debugging, all my Transactions failed, yet my AR balance went down.

I suspect
```
              quantity: await getFeeAmount(storedAddress, arweave)
```

At: https://github.com/th8ta/ArConnect/blob/50c2333b7dbe8579bd9408e90a73a038c9e183a4/src/utils/background.ts#L125

Does not take into account uncommitted Transactions, and continues to charge the higher fee

I suppose the normal person won't clip/sign() so quickly, but other developers may do so during debugging (especially at first)

While I do appreciate your work, it doesn't "feel so awesome" to be paying for failed Txes (especially when it seems like the root of the issue stems from ArConnect and arweave-js integration).

Had to go from the blockchain logs, wonder who hacked my wallet and was stealing funds unrelated to my tx, finally found mention of it on the FAQ, then had to go debug the source too.

I suppose my case is a little unique if this is the last developer facing bug :)  -- May consider a toggle switch during install/config for "tip the developer/VRT holders" that's a little more visible so it's a bit less "surprising".  Could even make the user "wait a little bit" if they decide to say no tip (just spin a box, show an advert, let them click to tip to speed up the UI).

**Comment by t8** [comment]
Hey @pctj101, 

Thanks so much for the feedback here! This is super useful feedback for us. @martonlederer and I discussed this briefly today, and he proposed the idea of automatically not charging a tip when the user is interacting with an application in `localhost`. 

Would love to hear your thoughts on this idea. Unfortunately there is no safe way to not charge a tip if a transaction failed directly. 

Thanks again for the feedback and developing with ArConnect!

Tate

**Comment by pctj101** [comment]
Due to some crypto libraries only loading over https, the localhost exception doesn't cover my use case.  However, I think it is a step in the right direction for most other developer usages.

In my case, it's easy enough for me to create a dev version that doesn't have the fee.  So I think your idea is enough as a start.

In any case, it would still be good to remove any "surprise" from users by displaying a note during install/config that they should expect such a fee and a link to more information (such as how the transaction will be tagged on the block explorer).

This way a user is able to recognize authorized fees.

If you really want to have a total pain, you could make the extension monitor for the ID to be committed to the blockchain before initiating a charge, but that sounds like a total pain to develop and would be wasteful on the network resource side.

**Comment by pctj101** [comment]
Might be more natural to have the user confirm the Tx sign() in a popup like metamask.  

That might be where you can put a note on the footer about the fee so that the user can contextually understand it.  

Also prevents an out of control application from doing an infinite sign/post loop without user knowledge and draining all funds.

This is especially important because small file uploads cost much less than even a $0.01 fee.  So a rapid drain loop would be made much worse by the relatively large fees.

**Comment by martonlederer** [comment]
We actually have notes on the fees. When you install the extension, we have a note that is (to me of course, maybe to others no) visible. I will work on a solution to display that even more clearly.

Sadly we cannot make the user confirm each transaction. The point of ArConnect is to not change the user experience of already existing dApps, so it provides a web2-like solution, where the user just has to log in once. I do have to mention, that we have the "allowances" feature to prevent dApps from draining your founds. There you can set a spending limit, and when that is reached, ArConnect will again display the auth/confirm popup

**Comment by pctj101** [comment]
I'll install the extension again and see if I can notice the note :)

On the web2-like solution, I think putting an "option for confirm" would be great for your roadmap.  I think your idea of no-confirm, and my idea of confirm both have particular use cases.  

For allowances, I think the principle is fine, but there's a User Experience improvement that could be made.  Currently the limit is specified in AR, which is technically correct, but humanly unconnectable.  It would be good to be able to set limits based on X GB or $X.  I understand fees may bleed into it, but a link to a web page to explain should be sufficient.

So I think an allowance such as:

* 25 MB (less fees)
* $1.50 (based on current exchange rates, less fees)

Would be more meaningful to the broader market (as ArConnect/ArWeave hopefully gets closer and closer to mass adoption by non-technical folks)

**Comment by pctj101** [comment]
I tested the extension reinstall and indeed there is a popup to the fees on the first page.

However, the focus of the first page is on passwords and config files.  So it's a different mental context to go looking for Fee Charts and fine print.

A separate screen / step which focuses on this topic would be better.  If that's too heavy during install, then at the first transaction prior to signing would be fine.  

I figure, if the user can survive config files and 24 word phrases, what's one more screen to get things straight?

It could be worded like this:
```
An Important Note From the Th8ta Team

ArConnect is FREE to use when clipping/saving content using our extension.

ArConnect takes a small TIP when a 3rd-party application.  
This TIP ensures our team can continue to develop this extension, 
which decreases the cost of development for all connecting applications.   
[More Information Link]

[I understand.  Continue]
```
