### ISSUE TITLE
Experience optimization of the create wallet page

### ISSUE THREAD

**Issue by unix** [arconnectio/ArConnect#58]
Hi guys, ArConnect really amazing product, congratulations on your success!

When creating a wallet, I found that when the user finishes creating the wallet, clicking on an area other than the Modal will cause the popup window to close. Once the user accidentally closes the Modal, they have to wait again for a while to generate a new wallet.
After going through the code I think the code that affects this behavior is here: [Welcome/App.tsx#L462](https://github.com/th8ta/ArConnect/blob/1475234160a3c05d199ae081e2971550c0c0c1db/src/views/Welcome/App.tsx#L462), Perhaps we can improve the user experience by adding a props(`disableBackdropClick`) to the Modal:

```
<Modal {...loadWalletsModal.bindings} disableBackdropClick>
  ...
</Modal>
```

----
Thank you for your work and for making me enjoy the convenience of Arweave even more!

**Comment by martonlederer** [comment]
Thank you that is a great suggestion :)

**Comment by martonlederer** [comment]
Not relevant anymore in 1.0
