### ISSUE TITLE
signature method returns a plain Object?

### ISSUE THREAD

**Issue by jim-toth** [arconnectio/ArConnect#59]
I'm trying to sign data items to bundle them into a single tx using `ArBundles` and i'm running into an issue using the `signature` method.  The return type of the method is `Promise<string>` but it's returning a plain Object.  I'm struggling to debug why :)

```typescript
async sign(message: Uint8Array): Promise<Uint8Array> {
  const signature = await window.arweaveWallet.signature(message, {
    name: "RSA-PSS",
    saltLength: 32,
  })
  console.log('SIGNING WITH THIS SIGNATURE', signature)

  return Buffer.from(signature) // This line will fail as signature is not a string as expected
}
```

This is running in a browser environment (Brave Version 1.34.81 Chromium: 97.0.4692.99 (Official Build) (64-bit))
`Buffer` is provided by a dependency in the `arbundles` package and implements `Uint8Array`

The return line in the above method will error with the following:

```
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
```

![image](https://user-images.githubusercontent.com/5704858/151249314-3e700eea-598e-44fd-b780-d325ea693bf4.png)

Any pointers or advice?  Thanks!

**Comment by martonlederer** [comment]
Apologies, we currently do not support bundles, but this will be an upcoming feature. That function is not for bundle signing.

**Comment by jim-toth** [comment]
@martonlederer Well I got it to work anyway :P  Bundle successfully posted locally with `arlocal` using ANS-104 Binary format

```typescript
async sign(message: Uint8Array): Promise<Uint8Array> {
  const signature = await window.arweaveWallet.signature(message, {
    name: "RSA-PSS",
    saltLength: 32,
  }) as any

  const signatureArray = []
  const keys = Object.keys(signature)

  for (let i = 0; i < keys.length; i++) {
    signatureArray.push(signature[keys[i]])
  }

  return Uint8Array.from(signatureArray)
}
```

**Comment by jim-toth** [comment]
I'm using `arbundles` and wrote a custom `Signer` and also re-implemented the `bundleAndSignData` method to use `Buffer` and it all works now

```typescript
      class ArweaveWalletSigner implements Signer {
        signatureType: number = SignatureConfig.ARWEAVE
        ownerLength: number = SIG_CONFIG[SignatureConfig.ARWEAVE].pubLength
        signatureLength: number = SIG_CONFIG[SignatureConfig.ARWEAVE].sigLength

        // TODO
        publicKey: Buffer

        // TODO ?
        pem?: string | Buffer | undefined

        constructor(publicKey: Buffer) {
          this.publicKey = publicKey
        }

        async sign(message: Uint8Array): Promise<Uint8Array> {
          const signature = await window.arweaveWallet.signature(message, {
            name: "RSA-PSS",
            saltLength: 32,
          }) as any

          const signatureArray = []
          const keys = Object.keys(signature)

          for (let i = 0; i < keys.length; i++) {
            signatureArray.push(signature[keys[i]])
          }

          return Uint8Array.from(signatureArray)
        }

        static async verify(
          pk: string,
          message: Uint8Array,
          signature: Uint8Array,
        ): Promise<boolean> {
          return await Arweave.crypto.verify(pk, message, signature)
        }
      }
```

**Comment by jim-toth** [comment]
My guess is that `signature` is attempting to return a `Uint8Array` but it's been JSON `stringified` and `parsed` or something similar.  Possibly because of the call message format between the extension's environment

**Comment by martonlederer** [comment]
Wow nice job! This will also help us implementing a specialized api for bundles in the future

**Comment by jim-toth** [comment]
> Wow nice job! This will also help us implementing a specialized api for bundles in the future

thanks!  Ultimately this issue is for the `signature` method returning a plain object instead of a `string` as suggested by the docs https://docs.th8ta.org/arconnect/functions#signature which is also reflected in the method's return type definition.

i'd like to move forward using the `signature` method as I outlined above but it seems to be a bug that it's returning a plain object.  I wouldn't want to run into breaking changes, although I could type check the return value for `string` for now

**Comment by martonlederer** [comment]
I will have to investigate why it's not consistent, I'll keep this issue open till then.

**Comment by jim-toth** [comment]
> I will have to investigate why it's not consistent, I'll keep this issue open till then.

thanks!  I think it might be more useful to instead change the return type to `Uint8Array` as that's what the input is expected to be and, at least for my use case, what i'd like it to use it as

i think it is returning a `Uint8Array` it's just been erroneously converted to a plain object or never re-instantiated as `Uint8Array` after getting the result from the extension environment
