### ISSUE TITLE
walletSwitch event doesn't fire unless page has ACCESS_ALL_ADDRESSES permission

### ISSUE THREAD

**Issue by jim-toth** [arconnectio/ArConnect#64]
Understandably, the ability for a page to to access all addresses in ArConnect should be behind a permission.  However, there's no way for the page to detect if the wallet was switched at all, even if it doesn't have permission to view the new address.

Would it be possible to fire the event anyway but not provide the new address?  This way, the page could revert to an un-authenticated state.

Alternatively, this could be solved by adding  a `walletDisconnected` event, fired when a wallet is switched but the new address isn't connected to the page or the page doesn't have `ACCESS_ALL_ADDRESSES` permission.

**Comment by martonlederer** [comment]
As noted in the [docs](https://github.com/th8ta/ArConnect#walletswitch), yes the event requires permissions. This is to not allow the oage to bypass a missing address permission. 

I do agree that it might be too much, to limit this with the access all addresses permission as well. I'll take this into consideration

**Comment by jim-toth** [comment]
@martonlederer I actually expected the event to fire but `e.detail.address` to be `null` or `undefined` if the `ACCESS_ALL_ADDRESSES` permission wasn't allowed.

**Comment by martonlederer** [comment]
Probably the best solution

**Comment by jim-toth** [comment]
❤️
