### ISSUE TITLE
`Uncaught Error: Mismatched anonymous define() module` on Brave/Firefox

### ISSUE THREAD

**Issue by flayks** [arconnectio/ArConnect#70]
When visiting some websites (typically French taxes or some online shops and specific websites like [SUTOM](https://sutom.nocle.fr)), ArConnect is literally blocking the website from running or login, which is very inconvenient as you could imagine.

The only error I've got on Brave or Firefox with ArConnect installed, visiting SUTOM is this:
```
Uncaught Error: Mismatched anonymous define() module: function(){return e}
https://requirejs.org/docs/errors.html#mismatch
```

**Comment by martonlederer** [comment]
Hey there, I will be checking on this as soon as possible. Thanks for reporting
