### ISSUE TITLE
Issue with displaying 'confetti' animation.

### ISSUE THREAD

**Issue by ppedziwiatr** [arconnectio/ArConnect#89]
Whenever there's an interaction with a wallet, a ton of error messages
<img width="1441" alt="image" src="https://user-images.githubusercontent.com/84311757/196701545-bbd10717-7359-4bb7-96d1-2eda843793d7.png">

is being logged in the console.

Instead of the 'arweave' "confetti" effect - a confetti of "broken image" icons is displayed.

ArConnect version 0.5.1 (tried reinstalling - did not help)
Chrome: Version 106.0.5249.119 (Official Build) (arm64)

Application is running locally.

**Comment by t8** [comment]
Thanks for the report, @ppedziwiatr! We'll take a look 👍
