### ISSUE TITLE
encrypt() and decrypt() APIs use own ArConnect-specific encryption methods

### ISSUE THREAD

**Issue by angrymouse** [arconnectio/ArConnect#90]
Is there any good reasons why ArConnect doesn't allow direct RSA encryption/decryption, without ArConnect's algorithm with adding symmetric keys there?

**Comment by martonlederer** [comment]
We haven't received any requests for this yet. Feel free to work on it tho :)

**Comment by angrymouse** [comment]
@martonlederer Thanks for reply! How do you think, how many apps are already using arconnect version, and should we add 2 new methods instead (encryptRSA, decryptRSA), because changing algorithm to default RSA encryption/decryption instead of ArConnect's version will result to breaking changes.

**Comment by martonlederer** [comment]
I'd like to hear the opinion of @jfbeats and @DanMacDonald  as well.

**Comment by jfbeats** [comment]
Hey Marton! 😀 The `encrypt` and `decrypt` for arweave.app already use the model @angrymouse is talking about so that people can implement their own protocols.

If you want to add them, I think you can do it without breaking changes by looking at the number of parameters for the function call, and just selecting between the old and new implementations depending on if the required params are provided or not.

**Comment by martonlederer** [comment]
Thanks @jfbeats, will proceed accordingly. 😀

**Comment by DanMacDonald** [comment]
Yeah, I have two codepaths for decrypting weavemails, one for arweave.app one for arconnect. It would be nice to combine them into one. With the wallet only performing an RSA encrypt, it frees the app up to use whatever flavor of AES (or other) encryption they like.

e.g. of what my code looks like right now... 

```js
export async function decryptMessage(message: PermamailData, arweave: Arweave): Promise<InboxItem> {
  let encryptedData = message.messageBlob;
  let walletType = walletService.getWalletType();
  let mailData = null;

  switch (walletType) {
    case WalletType.JWK:
    case WalletType.WalletConnector:
      // Split up the transaction data into the correct parts
      const symmetricKeyBytes: Uint8Array = new Uint8Array(encryptedData.slice(0, 512));
      const mailBytes: Uint8Array = new Uint8Array(encryptedData.slice(512));

      // Decrypt the symmetric key from the first part
      const symmetricKey = await walletService.decryptRSA(symmetricKeyBytes);

      // Use the symmetric key to decrypt the mail from the last part
      const decryptString = Arweave.utils.bufferToString(await Arweave.crypto.decrypt(mailBytes, symmetricKey));
      mailData = JSON.parse(decryptString);

    break;
    case WalletType.ArConnect:
      // ArConnect specific decrypt flow
      const stringData  = await window.arweaveWallet.decrypt(
        encryptedData, { algorithm: "RSA-OAEP", hash: "SHA-256" }
      );
      mailData = JSON.parse(decryptString);
    break;
    default:
      console.error(`Decrypting with unknown wallet type ${walletType}`);
    break;
  }
  ```

If ArConnect was only to perform RSA encrypt/decrypt this could all be collapsed to use the same 4 lines for all cases.
