### ISSUE TITLE
feat(gateway): broadcast gateway config changes to the window

### ISSUE THREAD

**Issue by dtfiedler** [arconnectio/ArConnect#97]
[Similar to `walletSwitch`](https://github.com/arconnectio/ArConnect/blob/fe1078bebcb7aef83a9bc884167124115228af26/types/index.d.ts#L145-L148), broadcast `GatewayConfig` and any changes to the window - this would allow dApps to let `arconnect` manage gateway configs globally vs. inter-app.

**Comment by atticusofsparta** [comment]
created a pr for this https://github.com/arconnectio/ArConnect/pull/99

**Comment by martonlederer** [comment]
Will be fixed in #115
